---
# COPY and this file to secrets.yml and modify as needed
development:
  DATABASE_URL: sqlite://db/local/development.db
  DB_KEY: 8kuAf0ztJFXrzNT9/6yPqXwmD3z8tOPzFpmf1ZONETU=
  MSG_KEY: ACQRYUR5xrDb4SZ7VH9J28cOj//Dv78VtvHOGLXxEEg=
  SECURE_SCHEME: HTTP

test:
  DATABASE_URL: sqlite://db/local/test.db
  DB_KEY: 8kuAf0ztJFXrzNT9/6yPqXwmD3z8tOPzFpmf1ZONETU=
  MSG_KEY: ACQRYUR5xrDb4SZ7VH9J28cOj//Dv78VtvHOGLXxEEg=
  SECURE_SCHEME: HTTP

production:
  DATABASE_URL: <do not set - assigned by production service>
  DB_KEY: <do not set - use `rake newkey:db` to generate a secret key for production>
  MSG_KEY: <do not set - use `rake newkey:msg` to generate a secret key for production>
  SECURE_SCHEME: HTTPS