---
development:
  DATABASE_URL: sqlite://db/local/development.db
  DB_KEY: 8kuAf0ztJFXrzNT9/6yPqXwmD3z8tOPzFpmf1ZONETU=

test:
  DATABASE_URL: sqlite://db/local/test.db
  DB_KEY: 8kuAf0ztJFXrzNT9/6yPqXwmD3z8tOPzFpmf1ZONETU=

production:
  DATABASE_URL: <do not set - assigned by production service>
  DB_KEY: <do not set - use `rake newkey:db` to generate a secret key for production>