---
# COPY and this file to secrets.yml and modify as needed
development:
  DATABASE_URL: sqlite://db/local/development.db
  DB_KEY: 8kuAf0ztJFXrzNT9/6yPqXwmD3z8tOPzFpmf1ZONETU=
  MSG_KEY: ACQRYUR5xrDb4SZ7VH9J28cOj//Dv78VtvHOGLXxEEg=
  SIGNING_KEY: E8a37tTbbsd6Anh70puF8JqkvTTGJwQOshWhEaVDo7s=
  VERIFY_KEY: HaJBppHRCbWY68xWK8C/SAuj2MSR85wdZivb0ObSBHg=
  MAILJET_FROM_EMAIL: lostnfound@yikuo.dev
  MAILJET_API_KEY: <API_KEY>
  MAILJET_API_SECRET: <API_SECRET>
  MAILJET_API_URL: https://api.mailjet.com/v3.1/send
  S3_ENDPOINT: <S3_ENDPOINT>
  S3_BUCKET: <S3_BUCKET>
  S3_ACCESS_KEY_ID: <ACCESS_KEY_ID>
  S3_SECRET_ACCESS_KEY: <SECRET_ACCESS_KEY>
  S3_REGION: <S3_REGION>
  SECURE_SCHEME: HTTP

test:
  DATABASE_URL: sqlite://db/local/test.db
  DB_KEY: 8kuAf0ztJFXrzNT9/6yPqXwmD3z8tOPzFpmf1ZONETU=
  MSG_KEY: ACQRYUR5xrDb4SZ7VH9J28cOj//Dv78VtvHOGLXxEEg=
  SIGNING_KEY: E8a37tTbbsd6Anh70puF8JqkvTTGJwQOshWhEaVDo7s=
  VERIFY_KEY: HaJBppHRCbWY68xWK8C/SAuj2MSR85wdZivb0ObSBHg=
  MAILJET_FROM_EMAIL: lostnfound@yikuo.dev
  MAILJET_API_KEY: <API_KEY>
  MAILJET_API_SECRET: <API_SECRET>
  MAILJET_API_URL: https://api.mailjet.com/v3.1/send
  S3_ENDPOINT: <S3_ENDPOINT>
  S3_BUCKET: <S3_BUCKET>
  S3_ACCESS_KEY_ID: <ACCESS_KEY_ID>
  S3_SECRET_ACCESS_KEY: <SECRET_ACCESS_KEY>
  S3_REGION: <S3_REGION>
  SECURE_SCHEME: HTTP

production:
  DATABASE_URL: <do not set - assigned by production service>
  DB_KEY: <do not set - use `rake newkey:db` to generate a secret key for production>
  MSG_KEY: <do not set - use `rake newkey:msg` to generate a secret key for production>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  MAILJET_FROM_EMAIL: lostnfound@yikuo.dev
  MAILJET_API_KEY: <API_KEY>
  MAILJET_API_SECRET: <API_SECRET>
  MAILJET_API_URL: https://api.mailjet.com/v3.1/send
  S3_ENDPOINT: <S3_ENDPOINT>
  S3_BUCKET: <S3_BUCKET>
  S3_ACCESS_KEY_ID: <ACCESS_KEY_ID>
  S3_SECRET_ACCESS_KEY: <SECRET_ACCESS_KEY>
  S3_REGION: <S3_REGION>
  SECURE_SCHEME: HTTPS